### ISSUE TITLE
happybase version 1.0 failing to import on python 2.7.10 or 3.5.2

### ISSUE THREAD

**Issue by uamadman** [wbolster/happybase#141]
For python 2.7.10 verion 0.9 functions properly and version 1.0 does not.
For python 3.5.2 version 0.9 will not install and version 1.0 throws the same error received from 2.7.10.
```
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
>>> import happybase
>>> happybase.__version__
'0.9'
```

Error code from happybase 1.0
```
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
>>> import happybase
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.1.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Python27_64\lib\site-packages\happybase\__init__.py", line 10, in <module>
    'Hbase_thrift')
  File "C:\Python27_64\lib\site-packages\thriftpy\parser\__init__.py", line 30, in load
    include_dir=include_dir)
  File "C:\Python27_64\lib\site-packages\thriftpy\parser\parser.py", line 496, in parse
    url_scheme))
ThriftParserError: ThriftPy does not support generating module with path in protocol 'c'
```

Error code from attempting to install happybase 0.9 and python 3.5.2
```
Collecting happybase==0.9
  Using cached happybase-0.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\**********\AppData\Local\Temp\pycharm-packaging\happybase\setup.py", line 5, in <module>
        execfile('happybase/_version.py')
    NameError: name 'execfile' is not defined
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in C:\Users\**********\AppData\Local\Temp\pycharm-packaging\happybase\

```
Error code from happybase 1.0 and python 3.5.2.
```
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32
>>> import happybase
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files (x86)\JetBrains\PyCharm 2016.1.4\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Python_Virtenv\Geospatial_Node\lib\site-packages\happybase\__init__.py", line 10, in <module>
    'Hbase_thrift')
  File "C:\Python_Virtenv\Geospatial_Node\lib\site-packages\thriftpy\parser\__init__.py", line 30, in load
    include_dir=include_dir)
  File "C:\Python_Virtenv\Geospatial_Node\lib\site-packages\thriftpy\parser\parser.py", line 496, in parse
    url_scheme))
thriftpy.parser.exc.ThriftParserError: ThriftPy does not support generating module with path in protocol 'c'
```

**Comment by wbolster** [comment]
this looks like an issue in thriftpy, which seemingly does not handle windows paths correctly.

please raise this issue with the thriftpy developers.

**Comment by wbolster** [comment]
oh, and 0.9 does not work on python 3, since py3 support is a 1.0 addition.

**Comment by bhaskarbhuyan** [comment]
Modify the parser code in the windows side. Go to your python installation folder's site packages (...\Lib\site-packages\thriftpy\parser.py) and then make changes in line no. 488 where you get this line

    if url_scheme == '':
and change this to:
      
    if len(url_scheme) <= 1:
