### ISSUE TITLE
cybin.ProtocolError: No protocol version header

### ISSUE THREAD

**Issue by sixiong** [wbolster/happybase#145]
the test code is just below:
```python
from happybase import Connection
conn = Connection("172.19.0.2",16000,autoconnect=False)
conn.open()
conn.create_table(
        'mytable',
        {'cf1': dict(max_versions=10),
        'cf2': dict(max_versions=1, block_cache_enabled=False),
        'cf3': dict(),  # use defaults
       }
)
```
The error message like this:
```bash
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/usr/local/lib/python2.7/dist-packages/happybase/connection.py", line 311, in create_table
    self.client.createTable(name, column_descriptors)
  File "/usr/local/lib/python2.7/dist-packages/thriftpy/thrift.py", line 198, in _req
    return self._recv(_api)
  File "/usr/local/lib/python2.7/dist-packages/thriftpy/thrift.py", line 210, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "thriftpy/protocol/cybin/cybin.pyx", line 439, in cybin.TCyBinaryProtocol.read_message_begin (thriftpy/protocol/cybin/cybin.c:6470)
cybin.ProtocolError: No protocol version header
```
I googled and find [this link in stackoverflow](http://stackoverflow.com/questions/39112236/cybin-protocolerror-no-protocol-version-header),but no one answers.Could anyone show the reason why I got this error?thanks

**Comment by wbolster** [comment]
correct to thrift, as the docs tell you

**Comment by sixiong** [comment]
en,I fixed, thanks
