### ISSUE TITLE
cybin.ProtocolError: No protocol version header

### ISSUE THREAD

**Issue by hariramesh9a** [wbolster/happybase#153]
Hi guys ,

I am getting below error while using happybase

Traceback (most recent call last):
  File "hbase.py", line 8, in <module>
    for key, data in table.scan():
  File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/happybase/table.py", line 381, in scan
    self.name, scan, {})
  File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/thriftpy/thrift.py", line 160, in _req
    return self._recv(_api)
  File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/thriftpy/thrift.py", line 172, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "thriftpy/protocol/cybin/cybin.pyx", line 439, in cybin.TCyBinaryProtocol.read_message_begin (thriftpy/protocol/cybin/cybin.c:6457)
cybin.ProtocolError: No protocol version header

my code
---------
import happybase
import json
connection = happybase.Connection('ip', 9099)
table = connection.table('rawdataingestion')
for key, data in table.scan():
    print key, data
    break

**Comment by wbolster** [comment]
connect to the thrift server, and use the right transport

**Comment by amod400** [comment]
May be someone would find it useful..

https://stackoverflow.com/a/49126005/3879254
