### ISSUE TITLE
ProtocolError: No protocol version header

### ISSUE THREAD

**Issue by hicomein** [wbolster/happybase#171]
```
Traceback (most recent call last):
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/root/.pycharm_helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/steveli/invest_graph_pyspark/database/load_stock_shareholders.py", line 245, in <module>
    result = load_circulated_shareholders_hbase(max_count=4)
  File "/home/steveli/invest_graph_pyspark/database/load_stock_shareholders.py", line 214, in load_circulated_shareholders_hbase
    for key, data in table.scan(filter="RowFilter(>=, 'binary:%s')" % end_dates_str):
  File "/usr/lib/python2.7/site-packages/happybase/table.py", line 402, in scan
    self.name, scan, {})
  File "/usr/lib64/python2.7/site-packages/thriftpy/thrift.py", line 198, in _req
    return self._recv(_api)
  File "/usr/lib64/python2.7/site-packages/thriftpy/thrift.py", line 210, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "thriftpy/protocol/cybin/cybin.pyx", line 439, in cybin.TCyBinaryProtocol.read_message_begin (thriftpy/protocol/cybin/cybin.c:6470)
cybin.ProtocolError: No protocol version header
```

How to solve this problem?

**Comment by wbolster** [comment]
there is no sample code. that does not help.

are you connecting to the thrift daemon, and using the correct transport options?

**Comment by cavities** [comment]
I has same error  when i use multiprocessing.Process get hbase data Traceback 
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-5-ae9831467bbd>", line 15, in hbase_reader
    for key,data in ret_cursor:
  File "/usr/local/lib/python3.5/dist-packages/happybase/table.py", line 434, in scan
    self.connection.client.scannerClose(scan_id)
  File "/usr/local/lib/python3.5/dist-packages/thriftpy/thrift.py", line 198, in _req
    return self._recv(_api)
  File "/usr/local/lib/python3.5/dist-packages/thriftpy/thrift.py", line 210, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "thriftpy/protocol/cybin/cybin.pyx", line 439, in cybin.TCyBinaryProtocol.read_message_begin (thriftpy/protocol/cybin/cybin.c:6470)
cybin.ProtocolError: No protocol version header
Process Process-8:
my source code like this:
`import multiprocessing
# 数据连接-----------------------------------------------------
connectionPool = happybase.ConnectionPool(size=3,host=hbase.thrift.ip,port=current_port)
#--------------------------------------------------------------
# multi process  return save in dict

return_manager = multiprocessing.Manager()
return_dict = return_manager.dict()


def hbase_reader(connectionPool,rp,table_name,return_save):
    with connectionPool.connection() as current_conn:
        conn = current_conn.table(table_name)
        ret_cursor = conn.scan(row_prefix=rp)
        for key,data in ret_cursor:
            return_dict[key] = data

def hbase_reader1(connectionPool,rp,table_name):
    ret = [connectionPool,rp,table_name]
    print(ret)
    return ret
table_name = 'MetaData'

async_list = [b'20160101',b'20160102']
jobs = []
for i in async_list:
    proc = multiprocessing.Process(target=hbase_reader,args=(connectionPool,i,table_name,return_list))
    jobs.append(proc)
    proc.start()
for i in jobs:
    i.join()

print(return_list)`

**Comment by cavities** [comment]
so will i do it ?

**Comment by wbolster** [comment]
what is your question? 

in https://github.com/wbolster/happybase/issues/171#issuecomment-359526091 i wrote:
> you can not share connections nor connection pools between multiple processes.

so you should create new connections in new processes. this is not a happybase problem. it applies to everything that cannot be shared between processes:  open file handles, network connections, and so on.
