### ISSUE TITLE
cybin.ProtocolError: No protocol version header

### ISSUE THREAD

**Issue by psobolewski** [wbolster/happybase#187]
When I try to run simple example:

```
import happybase
server = "server-address"
connection = happybase.Connection(server)
print connection.tables()
```
I got this exception:

```
Traceback (most recent call last):
  File "/root/hbase_urls.py", line 19, in <module>
    print connection.tables()
  File "/Library/Python/2.7/site-packages/happybase/connection.py", line 242, in tables
    names = self.client.getTableNames()
  File "/Library/Python/2.7/site-packages/thriftpy/thrift.py", line 198, in _req
    return self._recv(_api)
  File "/Library/Python/2.7/site-packages/thriftpy/thrift.py", line 210, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "thriftpy/protocol/cybin/cybin.pyx", line 439, in cybin.TCyBinaryProtocol.read_message_begin (thriftpy/protocol/cybin/cybin.c:6470)
cybin.ProtocolError: No protocol version header
```

happybase version = 1.1.0
hbase = 1.1.2 
hortonworks hadoop cluster = HDP-2.6.2.0

**Comment by wbolster** [comment]
likely wrong `transport` or your not connecting to the thrift server

**Comment by amod400** [comment]
Maybe someone would find it useful

https://stackoverflow.com/a/49126005/3879254
