### ISSUE TITLE
TTransportException(message='TSocket read 0 bytes', type=4) when I use happybase to connect my hbase.

### ISSUE THREAD

**Issue by calliwen** [wbolster/happybase#193]
I have checked that my hbase works. I can use hbase shell and I can use chrome to Hbase master-status on :localhost:16010. But when I use happybase to connect the host=localhost, port=9000.  It turns that:
ygao@logkit:~/work_job/LogKit$ python write_to_hbase.py
test--
start connect...
('--------', <happybase.connection.Connection object at 0x7feabca2ddd0>)
Traceback (most recent call last):
  File "write_to_hbase.py", line 46, in <module>
    conn, table = connect_to_hbase()
  File "write_to_hbase.py", line 38, in connect_to_hbase
    print( "available tables: ", conn.tables() )
  File "/home/ygao/anaconda2/lib/python2.7/site-packages/happybase/connection.py", line 242, in tables
    names = self.client.getTableNames()
  File "/home/ygao/anaconda2/lib/python2.7/site-packages/thriftpy/thrift.py", line 198, in _req
    return self._recv(_api)
  File "/home/ygao/anaconda2/lib/python2.7/site-packages/thriftpy/thrift.py", line 210, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "thriftpy/protocol/cybin/cybin.pyx", line 429, in cybin.TCyBinaryProtocol.read_message_begin
  File "thriftpy/protocol/cybin/cybin.pyx", line 60, in cybin.read_i32
  File "thriftpy/transport/buffered/cybuffered.pyx", line 65, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.c_read (thriftpy/transport/buffered/cybuffered.c:1881)
  File "thriftpy/transport/buffered/cybuffered.pyx", line 69, in thriftpy.transport.buffered.cybuffered.TCyBufferedTransport.read_trans (thriftpy/transport/buffered/cybuffered.c:1948)
  File "thriftpy/transport/cybase.pyx", line 61, in thriftpy.transport.cybase.TCyBuffer.read_trans
  File "/home/ygao/anaconda2/lib/python2.7/site-packages/thriftpy/transport/socket.py", line 125, in read
    message='TSocket read 0 bytes')
thriftpy.transport.TTransportException: TTransportException(message='TSocket read 0 bytes', type=4)

It fool me a few days. I am helpless for this issue.  So I turn to you for help. Thanks a lot.

**Comment by calliwen** [comment]
omg, it's my fault. I solved it by start the thrift server.
hbase thrift start -p 9090;
And, it should be that way to get the connection as fellow:
conn = happybase.Connection( host='localhost', port=9090, protocol='compact'  ) // the port is thrift server runs at.

**Comment by kadhriesh** [comment]
I am getting same error but I have specificed all the parameters correctly
