### ISSUE TITLE
Windows7, happybase encounter an error: thriftpy.parser.exc.ThriftParserError: ThriftPy does not support generating module with path in protocol 'c'

### ISSUE THREAD

**Issue by calliwen** [wbolster/happybase#195]
Traceback (most recent call last):
  File "get_hbase_data.py", line 3, in <module>
    import happybase
  File "C:\Anaconda3\lib\site-packages\happybase\__init__.py", line 10, in <module>
    'Hbase_thrift')
  File "C:\Anaconda3\lib\site-packages\thriftpy\parser\__init__.py", line 30, in load
    include_dir=include_dir)
  File "C:\Anaconda3\lib\site-packages\thriftpy\parser\parser.py", line 496, in parse
    url_scheme))
thriftpy.parser.exc.ThriftParserError: ThriftPy does not support generating module with path in protocol 'c'

I solved it by this page: https://blog.csdn.net/lhh08hasee/article/details/79283596

open the file C:\Program Files\python3.6\Lib\site-packages\thriftpy\parser
change the line 488:
      if url_scheme in ('c', ''): 
just make it work.

**Comment by wbolster** [comment]
so this is a thriftpy issue, not happybase
