### ISSUE TITLE
I use happybase = 1.1.0 in python 2.7.9，and I often encounter the following error。I don't know what's wrong

### ISSUE THREAD

**Issue by mathbugua** [wbolster/happybase#207]
Traceback (most recent call last):

    wal=False
  File "/data/apps/eggs/happybase-1.1.0-py2.7.egg/happybase/table.py", line 464, in put
    batch.put(row, data)
  File "/data/apps/eggs/happybase-1.1.0-py2.7.egg/happybase/batch.py", line 137, in __exit__
    self.send()
  File "/data/apps/eggs/happybase-1.1.0-py2.7.egg/happybase/batch.py", line 60, in send
    self._table.connection.client.mutateRows(self._table.name, bms, {})
  File "/data/apps/eggs/thriftpy-0.3.9-py2.7.egg/thriftpy/thrift.py", line 198, in _req
    return self._recv(_api)
  File "/data/apps/eggs/thriftpy-0.3.9-py2.7.egg/thriftpy/thrift.py", line 210, in _recv
    fname, mtype, rseqid = self._iprot.read_message_begin()
  File "/data/apps/eggs/thriftpy-0.3.9-py2.7.egg/thriftpy/protocol/compact.py", line 143, in read_message_begin
    proto_id = self.read_ubyte()
  File "/data/apps/eggs/thriftpy-0.3.9-py2.7.egg/thriftpy/protocol/compact.py", line 218, in read_ubyte
    result, = unpack('!B', self.trans.read(1))
  File "thriftpy/transport/framed/cyframed.pyx", line 100, in thriftpy.transport.framed.cyframed.TCyFramedTransport.read (thriftpy/transport/framed/cyframed.c:2178)
  File "thriftpy/transport/cybase.pyx", line 137, in thriftpy.transport.cybase.CyTransportBase.get_string (thriftpy/transport/cybase.c:2294)
  File "thriftpy/transport/framed/cyframed.pyx", line 48, in thriftpy.transport.framed.cyframed.TCyFramedTransport.c_read (thriftpy/transport/framed/cyframed.c:1526)
  File "thriftpy/transport/framed/cyframed.pyx", line 68, in thriftpy.transport.framed.cyframed.TCyFramedTransport.read_frame (thriftpy/transport/framed/cyframed.c:1716)
  File "thriftpy/transport/framed/cyframed.pyx", line 31, in thriftpy.transport.framed.cyframed.TCyFramedTransport.read_trans (thriftpy/transport/framed/cyframed.c:1254)
  File "thriftpy/transport/cybase.pyx", line 61, in thriftpy.transport.cybase.TCyBuffer.read_trans (thriftpy/transport/cybase.c:1472)
  File "/data/apps/eggs/thriftpy-0.3.9-py2.7.egg/thriftpy/transport/socket.py", line 108, in read
    buff = self.sock.recv(sz)
  File "/data/apps/eggs/gevent-1.1.2/gevent/_socket2.py", line 280, in recv
    self._wait(self._read_event)
  File "/data/apps/eggs/gevent-1.1.2/gevent/_socket2.py", line 179, in _wait
    self.hub.wait(watcher)
  File "/data/apps/eggs/gevent-1.1.2/gevent/hub.py", line 630, in wait
    result = waiter.get()
  File "/data/app/eggs/gevent-1.1.2/gevent/hub.py", line 878, in get
    return self.hub.switch()
  File "/data/apps/eggs/gevent-1.1.2/gevent/hub.py", line 609, in switch
    return greenlet.switch(self)
timeout: timed out

**Comment by mathbugua** [comment]
hello，I saw the source code，which has the design of the batch size. But，does not has explicit call interface. Will you have any follow-up plans？

**Comment by wbolster** [comment]
.send() is in the stack trace you shared, via `__exit__`. the context manager calls it

**Comment by mathbugua** [comment]
You aer right. By monitoring, when the errors occurs，the thrift server did not respond for a long time
![image](https://user-images.githubusercontent.com/18512781/51103371-69396c80-181d-11e9-851e-f857e967f1db.png)

**Comment by mathbugua** [comment]
hello @wbolster    I found a strange phenomenon，when encounter the above error，I restart my server (not hbase server)，the respond time of the thrift server will go low
