### ISSUE TITLE
BrokenPipeError: when creating a table

### ISSUE THREAD

**Issue by dangulod** [wbolster/happybase#228]
Hello, 

I am trying to connect and create a table in hbase with happybase. However, when I user `create_table` the next error appears. I wonder if someone has any clue of what is happening. 

Thanks in advance

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/XXXXX/venv/lib/python3.6/site-packages/happybase/connection.py", line 309, in create_table
    self.client.createTable(name, column_descriptors)
  File "/XXXXX/venv/lib/python3.6/site-packages/thriftpy2/thrift.py", line 216, in _req
    self._send(_api, **kwargs)
  File "/XXXXX/venv/lib/python3.6/site-packages/thriftpy2/thrift.py", line 227, in _send
    self._oprot.write_message_end()
  File "thriftpy2/protocol/cybin/cybin.pyx", line 463, in cybin.TCyBinaryProtocol.write_message_end
  File "thriftpy2/transport/buffered/cybuffered.pyx", line 80, in thriftpy2.transport.buffered.cybuffered.TCyBufferedTransport.c_flush
  File "/XXXXX/venv/lib/python3.6/site-packages/thriftpy2/transport/socket.py", line 136, in write
    self.sock.sendall(buff)
BrokenPipeError: [Errno 32] Broken pipe
```

And the code, I have used:

```python
import happybase as hb

connection = hb.Connection('XXXXXXXX, 2181)

families = {
    'cf1': dict(max_versions=10),
    'cf2': dict(max_versions=1, block_cache_enabled=False),
    'cf3': dict(),  # use defaults
}
connection.create_table('mytable', families)
```

**Comment by wbolster** [comment]
i think you're not talking to hbase's thrift1 service

**Comment by dangulod** [comment]
Thank you for your reply. Unfourtunately, I do not understand what you mean. Do you mean that I am using the wrong port or hostname?

I get those values from `/etc/hbase/conf/hbase-site.xml`, specifically in the property `hbase.zookeeper.quorum` for hostname and  `hbase.zookeeper.property.clientPort` for port.

Let me know if you need more information

**Comment by wbolster** [comment]
https://www.google.com/search?q=hbase+thrift

**Comment by dangulod** [comment]
Yeah, you are right. I changed the port and now raise another exception because of the `cybin.ProtocolError`, but I have another issue to follow. Thank you for your time.

**Comment by wbolster** [comment]
good luck!

**Comment by KaiquanMah** [comment]
Trying out both [elserj](https://community.cloudera.com/t5/user/viewprofilepage/user-id/35250) and [vjain](https://community.cloudera.com/t5/user/viewprofilepage/user-id/36175)'s fixes worked for me: https://community.cloudera.com/t5/Support-Questions/HBase-Thrift-configuring-port/m-p/117916
