### ISSUE TITLE
Test with HBase 0.98 (and add compat mode)

### ISSUE THREAD

**Issue by wbolster** [wbolster/happybase#59]
Happybase works fine with HBase 0.98 but does not support newly introduced features.

Implementing these new features (with proper tests) would be a nice to have.

**Comment by jeroenvlek** [comment]
@wbolster, are there any issues with 0.98 that you are already aware of? I ran the suite against my port of happybase to Python 3 (see output below) and hbase-0.98.8-hadoop2 and two tests failed. There are several potential sources of error here, so if you could already confirm that 0.98 has issues, then I can narrow down the problem.

```
(happybase)[jvlek@orochimaru happybase]$ make test
find coverage/ -mindepth 1 -delete
python $(which nosetests) ${TESTS}
tests.test_api.test_connection_compat ... ok
tests.test_api.test_timeout_arg ... ok
tests.test_api.test_enabling ... ok
tests.test_api.test_compaction ... ok
tests.test_api.test_prefix ... ok
tests.test_api.test_stringify ... ok
tests.test_api.test_table_listing ... ok
tests.test_api.test_table_regions ... ok
tests.test_api.test_invalid_table_create ... ok
tests.test_api.test_families ... ok
tests.test_api.test_put ... ok
tests.test_api.test_atomic_counters ... ERROR
ERROR

======================================================================
ERROR: tests.test_api.test_atomic_counters
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jvlek/.virtualenvs/happybase/lib/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/jvlek/dev/lib/happybase/tests/test_api.py", line 172, in test_atomic_counters
    table.counter_set(row, column, 0)
  File "/home/jvlek/dev/lib/happybase/happybase/table.py", line 540, in counter_set
    self.put(row, {column: pack_i64(value)})
  File "/home/jvlek/dev/lib/happybase/happybase/table.py", line 436, in put
    batch.put(row, data)
  File "/home/jvlek/dev/lib/happybase/happybase/batch.py", line 132, in __exit__
    self.send()
  File "/home/jvlek/dev/lib/happybase/happybase/batch.py", line 55, in send
    self._table.connection.client.mutateRows(self._table.name, bms, {})
  File "/home/jvlek/dev/lib/happybase/happybase/hbase/Hbase.py", line 1598, in mutateRows
    self.send_mutateRows(tableName, rowBatches, attributes)
  File "/home/jvlek/dev/lib/happybase/happybase/hbase/Hbase.py", line 1607, in send_mutateRows
    args.write(self._oprot)
  File "/home/jvlek/dev/lib/happybase/happybase/hbase/Hbase.py", line 7470, in write
    iter351.write(oprot)
  File "/home/jvlek/dev/lib/happybase/happybase/hbase/ttypes.py", line 589, in write
    iter6.write(oprot)
  File "/home/jvlek/dev/lib/happybase/happybase/hbase/ttypes.py", line 495, in write
    oprot.writeString(self.value)
  File "/home/jvlek/.virtualenvs/happybase/lib/python3.4/site-packages/thrift/protocol/TBinaryProtocol.py", line 122, in writeString
    encoded = bytearray(str, 'utf-8')
nose.proxy.TypeError: encoding or errors without a string argument
-------------------- >> begin captured logging << --------------------
happybase.batch: DEBUG: Sending batch for 'happybase_tests_tmp_test1' (1 mutations on 1 rows)
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test suite for <module 'tests.test_api' from '/home/jvlek/dev/lib/happybase/tests/test_api.py'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jvlek/.virtualenvs/happybase/lib/python3.4/site-packages/nose/suite.py", line 229, in run
    self.tearDown()
  File "/home/jvlek/.virtualenvs/happybase/lib/python3.4/site-packages/nose/suite.py", line 352, in tearDown
    self.teardownContext(ancestor)
  File "/home/jvlek/.virtualenvs/happybase/lib/python3.4/site-packages/nose/suite.py", line 368, in teardownContext
    try_run(context, names)
  File "/home/jvlek/.virtualenvs/happybase/lib/python3.4/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/jvlek/dev/lib/happybase/tests/test_api.py", line 76, in teardown_module
    connection.delete_table(TEST_TABLE_NAME, disable=True)
  File "/home/jvlek/dev/lib/happybase/happybase/connection.py", line 320, in delete_table
    if disable and self.is_table_enabled(name):
  File "/home/jvlek/dev/lib/happybase/happybase/connection.py", line 351, in is_table_enabled
    return self.client.isTableEnabled(name)
  File "/home/jvlek/dev/lib/happybase/happybase/hbase/Hbase.py", line 727, in isTableEnabled
    return self.recv_isTableEnabled()
  File "/home/jvlek/dev/lib/happybase/happybase/hbase/Hbase.py", line 744, in recv_isTableEnabled
    raise x
thrift.Thrift.TApplicationException: Negative length: -2147418111

Name                   Stmts   Miss  Cover   Missing
----------------------------------------------------
happybase.batch           57     18    68%   24, 27-31, 50, 87, 101-115, 130
happybase.connection     118      9    92%   111, 126, 170, 183-190, 321-324
happybase.pool            54     38    30%   54-78, 82-85, 91, 114-157
happybase.table          141     92    35%   23-24, 29-30, 67-68, 110-125, 146-169, 193-213, 294-407, 455-456, 570
happybase.util            30     12    60%   15-22, 31, 41, 67-71
tests                      0      0   100%   
tests.test_api           363    259    29%   49, 52-53, 77, 173-183, 187-208, 212-248, 252-291, 295-321, 325-352, 356-428, 432-444, 451-453, 457-480, 484-488, 493-540, 544-557, 561-578
tests.test_util           26     22    15%   11-29, 33-54
----------------------------------------------------
TOTAL                    789    450    43%   
----------------------------------------------------------------------
Ran 12 tests in 3.982s

FAILED (errors=2)
Makefile:12: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by jeroenvlek** [comment]
Ok, it is related to Thrift 1.0.0-dev. I will open a new issue for this and move my comments there. It boils down to this:

```
>>> from struct import Struct              
>>> bytearray(Struct('>q').pack(0), 'utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: encoding or errors without a string argument
```

It seems that the 'utf-8' encoding parameter in TBinaryProtocol causes the problems, which is new in 1.0.0-dev:

```python
## Thrift 0.9.2: lib/py/src/protocol/TBinaryProtocol.py ## 
def writeString(self, str):
  self.writeI32(len(str))
  self.trans.write(str)

## Thrift 1.0.0-dev: lib/py/src/protocol/TBinaryProtocol.py ## 
def writeString(self, str):
  encoded = bytearray(str, 'utf-8')
  self.writeI32(len(encoded))
  self.trans.write(encoded)
```

Shouldn't the integer passed to set_atomic_counter be send as a TType.I64? Of course that would mean a new message type, because it couldn't be send as a mutateRows_args.

**Comment by shubhra5** [comment]
Yeah !! facing same issue

**Comment by wbolster** [comment]
Well, perhaps you could run the test suite against 0.98 and report on the results...

**Comment by shubhra5** [comment]
I am using happybase-0.9, and in it's connection.py I can see option is available for 
COMPAT_MODES = ('0.90', '0.92', '0.94', '0.96'), 
not for 0.98. So it is giving me error there. Do we have any alternatives ?

**Comment by wbolster** [comment]
just use 0.96

    — Wouter

**Comment by samriang** [comment]
Is there any replacement available for happybase at the moment?
Looking for such tool for HBase v.0.98 and newer .. :/

**Comment by wbolster** [comment]
what makes you think you need a replacement? have you tried at all?

    — Wouter

--

**Comment by samriang** [comment]
Yep, I've tried ofc. Now HappyBase works smoothly, but I'm looking to the future.
Since u said that HB no more supported it looks not pretty wise to use it in serious production -____-

**Comment by wbolster** [comment]
I'm not sure where you got that happybase is supposedly "no more supported".

HBase Thrift is a stable interface, and Happybase targets that interface. What "supported in happybase" means is basically that it wraps most of the features that the Thrift API offers, and that it has been tested. Newer HBase versions may add new features, which may not be accessible from happybase since they haven't been implemented in happybase (yet).

Anyway, since the HBase Thrift API is stable, current happybase versions will work just fine with newer hbase versions.

Having a "0.98" compat mode in the code that really doesn't do anything than it would do with "0.96" would just be marketing.

**Comment by wbolster** [comment]
For clarity: Happybase _does_ work with HBase 0.98 just fine. 0.98-only features have not been added, that's all.

**Comment by samriang** [comment]
I got info about support from http://happybase.readthedocs.org/ 
Exactly, "You should know that I don’t use HappyBase myself anymore". Seems I misunderstood that point :)

**Comment by wbolster** [comment]
well i don't use all the software i ever wrote nowadays, doesn't mean it doesn't work anymore. ;)

**Comment by wbolster** [comment]
while happybase worked fine against hbase 0.98 when using the 0.96 compat mode, there is now a real 0.98 compat mode (see #155). closing this.
