### ISSUE TITLE
TApplicationException: scannerOpenWithScan failed: unknown result

### ISSUE THREAD

**Issue by wuyazi** [wbolster/happybase#79]
I start 3 threads, with threading.Thread(), and do scan at each thread. 
But only one can finished, others are exception, like that:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/hadoop/kintal/deploys2/tasks/init_location.py", line 109, in do_location
    location = get_location(row[1])
  File "/home/hadoop/kintal/deploys2/tasks/init_location.py", line 88, in get_location
    data = format_data(data)
  File "/home/hadoop/kintal/deploys2/tasks/init_location.py", line 50, in format_data
    location = get_sniffer_location(k[3:])
  File "/home/hadoop/kintal/deploys2/tasks/init_location.py", line 27, in get_sniffer_location
    for row in rows:
  File "/usr/lib/python2.6/site-packages/happybase/table.py", line 374, in scan
    self.name, scan, {})
  File "/usr/lib/python2.6/site-packages/happybase/hbase/Hbase.py", line 1919, in scannerOpenWithScan
    return self.recv_scannerOpenWithScan()
  File "/usr/lib/python2.6/site-packages/happybase/hbase/Hbase.py", line 1945, in recv_scannerOpenWithScan
    raise TApplicationException(TApplicationException.MISSING_RESULT, "scannerOpenWithScan failed: unknown result");
TApplicationException: scannerOpenWithScan failed: unknown result

```

**Comment by wuyazi** [comment]
i add threading.Lock(), it works

**Comment by wbolster** [comment]
A single `happybase.Connection` is not thread-safe, and this is by design. Each thread should either use a connection of its own, or temporary "lease" a connection from the built-in connection pool, as explained in the docs at http://happybase.readthedocs.org/en/latest/user.html#using-the-connection-pool
