### ISSUE TITLE
AWS Hbase:  Invalid method name: 'getTableNames'

### ISSUE THREAD

**Issue by ayanguha** [wbolster/happybase#98]
Hi

I am using Hbase 0.94.18 on AWS EMR. I am planning to use HappyBase as it looks very promising. Unfortunately I faced this issue on the very first attempt:

conn = happybase.Connection(port=9200,compat='0.94')
>>> conn.tables()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.6/site-packages/happybase/connection.py", line 238, in tables
    names = self.client.getTableNames()
  File "/usr/local/lib/python2.6/site-packages/happybase/hbase/Hbase.py", line 818, in getTableNames
    return self.recv_getTableNames()
  File "/usr/local/lib/python2.6/site-packages/happybase/hbase/Hbase.py", line 833, in recv_getTableNames
    raise x
thrift.Thrift.TApplicationException: Invalid method name: 'getTableNames'
>>>

Can you please help me?

**Comment by wbolster** [comment]
Are you sure you're using the right server? Thrift (not Thrift 2 btw!) is a separate daemon that runs alongside the HBase server processes itself. Also make sure the `transport=` arg matches the server configuration.

**Comment by aboyett** [comment]
On the master, you have to run `/home/hadoop/hbase/bin/hbase-daemon.sh start thrift`. Once the server is running, you can connect to it on port 9090
